# Configurrações gerais
title: Zero Trust
description: Segurança digital para todos.
url: "https://edumco.github.io"
baseurl: "/zero-trust"
timezone: "America/Recife"
lang: pt-BR
author: José Eduardo Montenegro
      
# Definição do tema
# theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes"

# Configurações do tema
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
logo: assets/img/security.png
github_username: edumco
search: true
breadcrumbs: true
date_format: "%Y-%m-%d"
enable_copy_code_button: true

author:
  name   : "José Eduardo"
  avatar : "/assets/img/profile.jpg"
  bio    : "QA Analyst e Bogueirinho"
  links:
    - label: "LinkedIn"
      icon: "/assets/img/linkedin.png"
      url: "https://www.linkedin.com/in/edumco/"
    - label: "GitHub"
      icon: "/assets/img/github.png"
      url: "https://github.com/edumco"

# Configuração da Paginação
paginate: 5
paginate_path: "/page:num/"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true